postgres:
  image: postgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  ports:
    - "5555:5432"
  expose:
    - "5432"

elixir:
  container_name: elixirdev
  build: .
  dockerfile: Dockerfile
  volumes:
    - c:/source/privat/testing/elixir:/elixir
  links:
    - postgres
  stdin_open: true
  ports:
    - "4000:4000"