version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  elixir:
    container_name: elixirdev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - c:/dev/elixir:/elixir
    links:
      - postgres
    stdin_open: true
    ports:
      - "4000:4000"